// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp415d1g7JxRDkdNKsQT7QPzG95f0D0bI',
    appId: '1:14004410587:web:27c5338fb3d274787594fe',
    messagingSenderId: '14004410587',
    projectId: 'flutter-mynotes-648c1',
    authDomain: 'flutter-mynotes-648c1.firebaseapp.com',
    storageBucket: 'flutter-mynotes-648c1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHlgXEYTVL_8vfSf25puB7zTvnlB51bDQ',
    appId: '1:14004410587:android:77667dc801c345317594fe',
    messagingSenderId: '14004410587',
    projectId: 'flutter-mynotes-648c1',
    storageBucket: 'flutter-mynotes-648c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCryjP3O7ep2HZvs-B9Aazk991zh3kJNFU',
    appId: '1:14004410587:ios:c8c9a147a20b8fdc7594fe',
    messagingSenderId: '14004410587',
    projectId: 'flutter-mynotes-648c1',
    storageBucket: 'flutter-mynotes-648c1.firebasestorage.app',
    iosBundleId: 'com.test.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCryjP3O7ep2HZvs-B9Aazk991zh3kJNFU',
    appId: '1:14004410587:ios:c8c9a147a20b8fdc7594fe',
    messagingSenderId: '14004410587',
    projectId: 'flutter-mynotes-648c1',
    storageBucket: 'flutter-mynotes-648c1.firebasestorage.app',
    iosBundleId: 'com.test.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp415d1g7JxRDkdNKsQT7QPzG95f0D0bI',
    appId: '1:14004410587:web:cdfa8c621c34436a7594fe',
    messagingSenderId: '14004410587',
    projectId: 'flutter-mynotes-648c1',
    authDomain: 'flutter-mynotes-648c1.firebaseapp.com',
    storageBucket: 'flutter-mynotes-648c1.firebasestorage.app',
  );
}
